/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url = uri("https://repo.akka.io/maven")
    }
}

dependencies {
    implementation("org.scala-lang:scala3-compiler_3:3.4.0")
    // This dependency is used by the application.
    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.1-jre")

    // Use Scalatest for testing our library
    testImplementation("org.scalatest:scalatest_3:3.2.10")
    testImplementation("org.scalatestplus:junit-4-13_3:3.2.10.0")
    testRuntimeOnly("org.scala-lang.modules:scala-xml_3:2.0.1")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Assginment 3 - Akka
    implementation(platform("com.typesafe.akka:akka-bom_2.13:2.9.3"))

    implementation("com.typesafe.akka:akka-persistence-typed_2.13")
    testImplementation("com.typesafe.akka:akka-persistence-testkit_2.13")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
